import { useState } from "react";
import { X, User, Truck } from "lucide-react";
import { DeliveryTimeline } from "../components/DeliveryTimeline";
import { NotificationPanel } from "../components/NotificationPanel";
import { FEATURED_ROUTE_GROUPS } from "../data/trail";
import { journeyLabel } from "../lib/format";
import type { JourneyCart, Page } from "../types";

export function MyPage({ setPage, carts, onPayCart }: { setPage: (p: Page) => void; carts: JourneyCart[]; onPayCart: (id: string) => void }) {
  const [tab, setTab] = useState("trips");
  const [paying, setPaying] = useState<string | null>(null);
  const selectedCart = carts.find(c => c.id === paying);
  const confirmed = carts.filter(c => c.status === "CONFIRMED");
  const cartItems = carts.filter(c => c.status === "CART");
  const completePay = () => { if (paying) { onPayCart(paying); setPaying(null); } };
  return (
    <div className="pt-16 min-h-screen bg-background">
      <div className="bg-surface-dark text-white py-12"><div className="max-w-7xl mx-auto px-4 sm:px-6 flex items-center justify-between gap-6"><div className="flex items-center gap-4"><div className="w-14 h-14 bg-accent rounded-full flex items-center justify-center"><User size={24} /></div><div><h1 className="text-2xl font-bold">김트레커님의 마이페이지</h1><p className="text-white/60 text-sm">내 여행 일정에서 장바구니 결제와 예약 상세를 확인합니다.</p></div></div><button onClick={() => { setPage("booking"); window.scrollTo(0,0); }} className="bg-primary px-5 py-3 rounded font-bold">새 여정 구성</button></div></div>
      <div className="max-w-7xl mx-auto px-4 sm:px-6 py-10">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">{[[String(cartItems.length),"장바구니"],[String(confirmed.length),"예약확정"],[`₩${carts.reduce((s,c)=>s+c.total,0).toLocaleString()}`,"총 결제 예정"],["100개","일일 배송 캐파"]].map(([v,l])=><div key={l} className="bg-card rounded-lg border border-foreground/10 p-5"><p className="text-2xl font-bold text-foreground">{v}</p><p className="text-xs text-muted-foreground mt-1">{l}</p></div>)}</div>
        <div className="flex gap-4 mb-8 border-b border-foreground/10 overflow-x-auto">{[["trips","내 여행 일정"],["delivery","배송 현황"],["profile","내 프로필"],["password","비밀번호 변경"],["logout","로그아웃/탈퇴"]].map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`pb-3 text-sm font-semibold border-b-2 whitespace-nowrap ${tab===id?"border-foreground text-foreground":"border-transparent text-muted-foreground"}`}>{label}</button>)}</div>
        {tab === "trips" && <div className="space-y-5">{carts.length === 0 && <div className="bg-card rounded-lg border border-foreground/10 p-10 text-center"><p className="text-muted-foreground mb-4">저장된 여정이 없습니다.</p><button onClick={()=>setPage("booking")} className="bg-surface-dark text-white px-5 py-3 rounded font-bold">여정 구성하기</button></div>}{carts.map(cart => { const g=FEATURED_ROUTE_GROUPS.find(x=>x.key===cart.routeKey) || FEATURED_ROUTE_GROUPS[0]; return <div key={cart.id} className="bg-card rounded-lg border border-foreground/10 p-6"><div className="flex flex-col lg:flex-row lg:items-start justify-between gap-5"><div><div className="flex items-center gap-2 mb-2"><span className="text-xs font-mono text-muted-foreground">{cart.id}</span><span className={`text-xs font-bold px-2 py-1 rounded ${cart.status==="CONFIRMED"?"bg-green-100 text-green-800":"bg-secondary text-label"}`}>{cart.status==="CONFIRMED"?"예약확정":"장바구니"}</span>{cart.reservationNo && <span className="text-xs font-bold text-foreground">예약번호 {cart.reservationNo}</span>}</div><h3 className="font-bold text-foreground text-lg">{g.title} · {cart.schedule}</h3><p className="text-sm text-muted-foreground mt-1">{cart.days.length}일 · 가방 {cart.days.reduce((s,d)=>s+d.bags,0)}개 · ₩{cart.total.toLocaleString()}</p></div><div className="flex gap-2">{cart.status==="CART" && <button onClick={()=>setPaying(cart.id)} className="bg-primary text-white px-4 py-2 rounded font-bold text-sm">결제 진행</button>}<button className="border border-foreground/20 px-4 py-2 rounded text-sm font-bold text-foreground">상세 확인</button></div></div><div className="mt-5 grid grid-cols-1 md:grid-cols-2 gap-3">{cart.days.map(d => <div key={`${cart.id}-${d.day}`} className="bg-background rounded p-3 text-xs"><p className="font-bold text-foreground mb-1">{journeyLabel(d.day)} · {d.date} · {d.sectionId}구간</p><p className="text-muted-foreground">픽업 {d.pickup}</p><p className="text-muted-foreground">드롭 {d.dropoff}</p><p className="text-muted-foreground">숙소 {d.stay === "직접 입력" ? d.customStay : d.stay} · 가방 {d.bags}개 {d.bus ? "· 버스 연계" : ""}</p></div>)}</div></div>; })}</div>}
        {tab === "delivery" && <div className="space-y-6">{confirmed.length === 0 ? <div className="bg-card rounded-xl border border-foreground/10 p-10 text-center"><Truck size={34} className="mx-auto text-accent mb-3" /><h2 className="font-bold text-foreground text-xl">배송 현황을 확인할 예약이 없습니다.</h2><p className="text-sm text-muted-foreground mt-2">결제 완료 후 예약 단위의 일자별 배송 현황이 표시됩니다.</p></div> : <>{confirmed.map(cart => <div key={`${cart.id}-status`} className="grid grid-cols-1 xl:grid-cols-[1fr_330px] gap-6"><div><div className="mb-4"><p className="text-xs text-label font-bold tracking-widest">DELIVERY STATUS · {cart.reservationNo}</p><h2 className="text-2xl font-bold text-foreground mt-1">{(FEATURED_ROUTE_GROUPS.find(g => g.key === cart.routeKey) || FEATURED_ROUTE_GROUPS[0]).title} 배송 현황</h2></div><DeliveryTimeline cart={cart} /></div><NotificationPanel cart={cart} /></div>)}</>}</div>}
        {tab === "profile" && <div className="bg-card rounded-lg border border-foreground/10 p-6 max-w-2xl"><h2 className="font-bold text-foreground text-xl mb-4">내 프로필</h2><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><input defaultValue="김트레커" className="border rounded p-3"/><input defaultValue="010-1234-5678" className="border rounded p-3"/><input defaultValue="member@donkeyroad.kr" className="border rounded p-3 sm:col-span-2"/></div></div>}
        {tab === "password" && <div className="bg-card rounded-lg border border-foreground/10 p-6 max-w-xl"><h2 className="font-bold text-foreground text-xl mb-4">비밀번호 변경</h2><input placeholder="현재 비밀번호" type="password" className="w-full border rounded p-3 mb-3"/><input placeholder="새 비밀번호" type="password" className="w-full border rounded p-3 mb-3"/><button className="bg-surface-dark text-white px-5 py-3 rounded font-bold">변경 완료</button></div>}
        {tab === "logout" && <div className="bg-card rounded-lg border border-foreground/10 p-6 max-w-xl"><h2 className="font-bold text-foreground text-xl mb-4">계정 관리</h2><button className="border border-foreground text-foreground px-5 py-3 rounded font-bold mr-2">로그아웃</button><button className="border border-red-300 text-red-700 px-5 py-3 rounded font-bold">회원 탈퇴</button></div>}
      </div>
      {selectedCart && <div className="fixed inset-0 z-[70] bg-black/50 flex items-center justify-center p-4"><div className="bg-card rounded-xl max-w-2xl w-full p-6"><div className="flex items-center justify-between mb-4"><h2 className="text-2xl font-bold text-foreground">토스페이먼츠 결제위젯 목업</h2><button onClick={()=>setPaying(null)}><X size={22}/></button></div><div className="bg-background rounded-lg p-5 mb-4"><p className="text-sm text-muted-foreground">결제 금액</p><p className="text-3xl font-bold text-foreground">₩{selectedCart.total.toLocaleString()}</p><div className="grid grid-cols-3 gap-2 mt-4">{["카드", "간편결제", "계좌이체"].map(m=><button key={m} className="bg-card border rounded p-3 font-bold text-foreground">{m}</button>)}</div></div><div className="border border-accent/30 bg-secondary rounded p-4 text-xs text-muted-foreground mb-4">첫 픽업 24시간 전 100% 환불 · 24시간 이내 환불 불가 · 운영 중단 시 100% 환불</div><button onClick={completePay} className="w-full bg-surface-dark text-white py-3 rounded font-bold">결제 승인 완료 처리</button></div></div>}
    </div>
  );
}
